name: Build GH Pages

on:
  workflow_call:

jobs:
  initialize:
    name: Checkout and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: ^7.0.0

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Set up project
        run: pnpm install

      - name: Run linting
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Build Public files
        run: pnpm build

      - name: Archive public assets
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          retention-days: 1

  deploy_public_assets:
    name: Deploy public assets
    runs-on: ubuntu-latest
    needs: initialize
    steps:
      - name: Checkout code repo
        uses: actions/checkout@v3

      - name: Download public assets
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Set up git credentials
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
        run: |
          git config --local user.name "$USER_NAME"
          git config --local user.email "$USER_EMAIL"
      - name: Deploy to GitHub Pages
        env:
          ACCESS_TOKEN: ${{ github.token }}
          DEPLOY_BRANCH: gh-pages
          STATIC_FOLDER: dist
        run: |
          bash ./.github/workflows/build.bash
