name: Build GH Pages

on:
  workflow_call:

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  initialize:
    name: Checkout and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^7.0.0

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Set up project
        run: pnpm install

      - name: Build Public files
        run: pnpm build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'

  deploy_public_assets:
    name: Deploy public assets
    runs-on: ubuntu-latest
    needs: initialize
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
