name: 'Deployment Action: Build and Deploy GH Page'

on:
  push:
    branches:
      - master

jobs:
  test-and-lint:
    uses: ./.github/workflows/test-and-lint.yml
  deploy:
    needs: test-and-lint
    uses: ./.github/workflows/build-and-deploy.yml
    secrets: inherit
